services:
  web:
    build:
      context: .
      dockerfile: dev.web.Dockerfile
    container_name: dan-dan-web
    ports:
      - "5173:5173"
    volumes:
      - ./web:/web
    working_dir: /web
    stdin_open: true
    tty: true
    command: sh -c "npm install && npm run dev"
  backend:
    build:
      context: .
      dockerfile: dev.backend.Dockerfile
    container_name: dan-dan-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend
      - ./backend/.docker/bundle:/usr/local/bundle
    working_dir: /backend
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/dan_dan_backend_development
      BUNDLE_BIN: /usr/local/bundle/bin
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "./bin/docker-start"

  db:
    image: postgres:16
    container_name: dan-dan-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dan_dan_backend_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dan_dan_backend_development"]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  postgres_data:
